### ISSUE TITLE
Can't import tti-polyfill from Node JS.

### ISSUE THREAD

**Issue by Vasikaran** [GoogleChrome/tti-polyfill#4]
Your **package.json** file's main key point **tti-polyfill.js**. But there is no export method. So when I try to import **tti-polyfill** I received only empty object. How to I use **tti-polyfill** from Node JS.

When I changed main key from **tti-polyfill.js** to **src/index.js** then its working fine.

**Comment by philipwalton** [comment]
Thanks, this was happening because the umd code got mangled by closure compiler. It should be fixed now with version 0.2.1.

**Comment by Vasikaran** [comment]
Now I need this. So, I have installed your package, then modified that by my requirement, then working on it.
